#!/usr/bin/env bash
#SBATCH -A NAISS2025-22-517
#SBATCH -p alvis
#SBATCH -t 0-02:00:00
#SBATCH --gpus-per-node=A40:1
#SBATCH --cpus-per-task=8
#SBATCH --array=0-95%4
#SBATCH --job-name=perch_infer_array
#SBATCH --chdir=/cephyr/users/sheilaho/Alvis/rewilding_madagascar
#SBATCH --output=/cephyr/users/sheilaho/Alvis/rewilding_madagascar/logs/%x_%A_%a.out
#SBATCH --error=/cephyr/users/sheilaho/Alvis/rewilding_madagascar/logs/%x_%A_%a.err

set -euo pipefail

echo "PWD in job: $(pwd)"
echo "Host: $(hostname)"
echo "Started: $(date)"

bash scripts/run_perch2_inference_array

echo "Finished: $(date)"