#!/usr/bin/env bash
#SBATCH -A NAISS2025-22-517
#SBATCH -p alvis
#SBATCH -t 0-02:00:00
#SBATCH --gpus-per-node=A40:1
#SBATCH --cpus-per-task=8
#SBATCH --job-name=perch_infer_test
#SBATCH --chdir=/cephyr/users/sheilaho/Alvis/rewilding_madagascar
#SBATCH --output=/cephyr/users/sheilaho/Alvis/rewilding_madagascar/logs/%x_%j.out
#SBATCH --error=/cephyr/users/sheilaho/Alvis/rewilding_madagascar/logs/%x_%j.err

set -euo pipefail

echo "PWD in job: $(pwd)"
echo "Host: $(hostname)"
echo "Started: $(date)"

apptainer exec --nv /cephyr/users/sheilaho/Alvis/perch2.sif \
    python -u scripts/run_perch2_inference.py \
      --inventory_csv metadata/file_inventory_mimer.csv \
      --recorder_key Ankafobe_KBB_A_KBB02 \
      --out_dir_predictions results/predictions_by_recorder \
      --out_dir_review results/review_top20_by_recorder

echo "Finished: $(date)"